import type { Metadata } from 'next';
import { Oswald, Rubik } from 'next/font/google';
import '../assets/Circe/stylesheet.css';

const oswaldSans = Oswald({
  variable: '--fat-font',
  subsets: ['cyrillic', 'latin'],
});

const rubikFont = Rubik({
  variable: '--main-font',
  subsets: ['cyrillic', 'latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${oswaldSans.variable} ${rubikFont.variable}`}>
        {children}
      </body>
    </html>
  );
}
